apiVersion: v1
kind: Service
metadata:
  name: postgres # Must match `.spec.serviceName` in the StatefulSet
spec:
  selector:
    app: postgres # Must match `.spec.template.metadata.labels.app` in the StatefulSet
  ports:
    - port: 5432
      name: postgres
  clusterIP: None # Headless service to enable stable network ID for each pod
